### ISSUE TITLE
translation change not working

### ISSUE THREAD

**Issue by ruettenm** [yankouskia/localize-react#5] opened 2020-04-10 07:40 UTC
Hi, 

in my app I'm trying to implement a language switch. But for some reason the translations are not changing when the **LocalizationProvider** is getting an other local.

```
class App extends React.Component<{}, { language: 'de' | 'en' }> {
    constructor(props) {
        super(props)
        this.state = { language: 'en' }
    }

    public render() {
        return (
            <LocalizationProvider
                locale={this.state.language}
                translations={translations}
            >
                <Header language={this.state.language} setLanguage={this.setLanguage}/>
                [...some content]
            </LocalizationProvider>
        )
    }

    private setLanguage = (language: 'de' | 'en') => {
        this.setState({ language })
    }
}
```

Do you have an idea how to solve this?

Thanks
Matthias

**Comment by ruettenm** [comment] 2020-04-10 19:43
I just had a look into your code and found the issue. It happens because you implemented the caching.

We you change the local the cache still returns the cached result from the previous execution.

**Comment by ruettenm** [comment] 2020-04-10 19:48
one solution could be to also pass through the local to the memoize function:

`export function memoize(fn, local) {`

and change the cache structure like this:

`TRANSLATION_CACHE[local][cacheKey]`

What do you think @yankouskia ?

**Comment by ruettenm** [comment] 2020-04-10 20:05
There is also an other issue because of the caching. When you have a webpack project with hot module reloading (HMR) the HMR is not working when you have changes in the translations.

Would be cool if it's possible to disable the caching on local at all.

**Comment by yankouskia** [comment] 2020-04-11 17:35
@ruettenm That's a nice catch, thanks for reporting! Will notify once it's fixed. Should be done shortly

**Comment by yankouskia** [comment] 2020-04-11 18:21
@ruettenm Version 1.4 is published. Please take a look, if it's working for you now:
1. `disableCache` key is added on `Provider`. So you could pass `true` there on your dev environment
2. Changing translations / locale on runtime will cause to clearing cache, so message will be updated.

**Comment by yankouskia** [comment] 2020-04-17 02:29
closing as fixed

**Closed by yankouskia** 2020-04-17 02:29 UTC

**Comment by ruettenm** [comment] 2020-04-17 06:22
Sorry, I forgot to give you feedback. The disableCache prop is working for me 👍 

I had a problem with the cache clearing (there was no re-rendering of my application). I'll try to figure out if it's a problem of my app our your library and will come back to you.

**Comment by yankouskia** [comment] 2020-04-17 17:53
@ruettenm if your component is updated - it should clear cache:
https://github.com/yankouskia/localize-react/blob/master/src/Provider.test.js#L246

**Comment by ruettenm** [comment] 2020-04-17 22:36
Yeah, I saw the unit test 👍  But for some reason the component is not rerendert. Or is rerendert before the clean cache. I'll have a deeper look and come back to you.

**Comment by Staicul** [comment] 2020-07-03 19:07
@ruettenm I'm facing the same problem. Did you find a way to get around it?

**Comment by yankouskia** [comment] 2020-07-04 19:45
@Staicul could you post a part of code to reproduce it?

**Comment by Staicul** [comment] 2020-07-05 10:30
Hi, @yankouskia ! I created [this project](https://github.com/Staicul/localize-issue.git) where you can reproduce the issue.

Passing scenario: default is EN. Click once on RO -> works. Click once on EN -> works;
Failing scenario: default is EN. Click once on EN -> nothing happens (normal). Click once on RO -> nothing changes in the page. Console log says state.language is RO. Click RO once again -> works.
So if any of the flags is clicked twice(or more) in a row, it takes two clicks on the other one to actually view the translated page. Why doesn't it rerender properly from the first click? The state.language is always the proper one before the render method is called.

**Comment by ruettenm** [comment] 2020-07-06 06:37
Hi, sorry for the delayed answer. I used this library only in a small hobby project and did not continue working on it.

But I can try to find some time to find the issue in the next days. I remember that I already fond something out :-)

**Comment by yankouskia** [comment] 2020-07-07 10:20
@Staicul I will take a look shortly and will let you know, thank you for posting!

**Comment by Staicul** [comment] 2020-07-15 20:46
Hi @yankouskia , @ruettenm ! Any updates on this?

**Comment by yankouskia** [comment] 2020-07-24 07:09
@Staicul Yeah, I have downloaded the project above and was not able to reproduce the issue. Have not changed anything and it just works. GIF attached
![change-locale](https://user-images.githubusercontent.com/10101073/88367941-a200bd00-cd95-11ea-843f-e066ade1b2df.gif)

**Comment by Staicul** [comment] 2020-07-24 11:37
@yankouskia It works properly if you only press each of them once.
Try pressing one of the flags twice or more, then press the other one only once. The language will not change. You will need to press it twice for the language to be switched back.
